In [1]:
import numpy as np


In [2]:
url_lengths = np.array([24, 34, 19, 2, 40])
print()
url_lengths.shape

(5,)

In [3]:
url_lengths.shape

(5,)

In [4]:
url_lengths

array([24, 34, 19,  2, 40])

In [5]:
url_lengths = np.array([24, 34, 19, 2, 40])
print()

In [6]:
url_lengths * 2 

array([48, 68, 38,  4, 80])

In [7]:
url_lengths - 3

array([21, 31, 16, -1, 37])

In [8]:
url_lengths % 3

array([0, 1, 1, 2, 1])

In [9]:
url_lengths.dtype

dtype('int64')

In [10]:
url_lengths = np.array([24, 34, 19, 2, 40], dtype=float)

In [11]:
url_lengths % 3

array([0., 1., 1., 2., 1.])

In [12]:
url_lengths2 = np.array([24, 34, 19, 2, 40], dtype=float)

In [13]:
url_lengths2 % 3

array([0., 1., 1., 2., 1.])

In [14]:
url_lengths2.dtype

dtype('float64')

In [15]:
url_lengths2/3

array([ 8.        , 11.33333333,  6.33333333,  0.66666667, 13.33333333])

In [16]:
url_lengths[0]

np.float64(24.0)

In [17]:
url_lengths[2:3]

array([19.])

In [18]:
url_lengths[2:4]

array([19.,  2.])

In [19]:
url_lengths[1:]

array([34., 19.,  2., 40.])

In [20]:
url_lengths[:-1]

array([24., 34., 19.,  2.])

In [21]:
url_lengths[-1]

np.float64(40.0)

In [22]:
url_lengths[-2,-1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [23]:
url_lengths[-2:-1]

array([2.])

In [24]:
url_lengths[-2:]

array([ 2., 40.])

In [26]:
url_feature = np.array([[24, 34, 19, 2, 40], [24, 34, 19, 2, 40]])

In [27]:
url_feature.shape

(2, 5)

In [29]:
url_feature.dtype

dtype('int64')

In [30]:
url_feature[1,1]

np.int64(34)

In [31]:
url_feature[1,3]

np.int64(2)

In [32]:
url_feature[1,]

array([24, 34, 19,  2, 40])

In [33]:
url_feature[0]

array([24, 34, 19,  2, 40])

In [34]:
url_features = np.array([[4, 19, 4, 61, 59], [24, 34, 19, 2, 40]])

In [35]:
url_features[1,3]

np.int64(2)

In [36]:
url_features.shape

(2, 5)

In [37]:
url_features[0:]

array([[34, 19,  4, 61, 59],
       [24, 34, 19,  2, 40]])

In [38]:
url_features[0:0]

array([], shape=(0, 5), dtype=int64)

In [39]:
url_features[0:1]

array([[34, 19,  4, 61, 59]])

In [40]:
url_features[:,0]

array([34, 24])

In [41]:
url_features.T

array([[34, 24],
       [19, 34],
       [ 4, 19],
       [61,  2],
       [59, 40]])

In [42]:
url_features.shape

(2, 5)

In [43]:
url_features.shape

(2, 5)

In [44]:
url_features.T.shape

(5, 2)

In [45]:
weights = np.array([[34, 19,  4],
       [24, 34, 19], [23, 139,  297], [21, 46,  98], [11, 18,  72]])

In [46]:
weights.shape

(5, 3)

In [47]:
url_features@weights

array([[ 3634,  5716, 11911],
       [ 2551,  5065,  9461]])

In [48]:
(url_features[1,3] - url_lengths.min()) /(url_lengths.max()- url_lengths.min())

np.float64(0.0)

In [49]:
(url_lengths[1:3] - url_lengths.min()) /(url_lengths.max()- url_lengths.min())

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [50]:
(url_lengths - url_lengths.min()) /(url_lengths.max()- url_lengths.min())

array([0.57894737, 0.84210526, 0.44736842, 0.        , 1.        ])

In [51]:
(url_lengths -url_lengths.mean())/ url_lengths.std()

array([ 0.01520748,  0.77558131, -0.36497944, -1.65761495,  1.23180561])

In [52]:
dataset = np.array([[13, 45, 736], [35, 68, 6], [71, 111, 56]])

In [53]:
means = np.array([1, 5, 234])

In [54]:
dataset - means

array([[  12,   40,  502],
       [  34,   63, -228],
       [  70,  106, -178]])